### ISSUE TITLE
team rice heroes

### ISSUE THREAD

**Issue by dagon11235** [msudesign/Senior-Design-3D-Printing#30]
[rice heroes.zip](https://github.com/msudesign/Senior-Design-3D-Printing/files/1858685/rice.heroes.zip)

**Comment by msudesign** [comment]
Your print will start tomorrow, we are down to one printer at the moment.

**Comment by msudesign** [comment]
Please check the box files.
When importing them, it is like they are way over scaled.
The display is printing now.

**Comment by dagon11235** [comment]
[round_box.zip](https://github.com/msudesign/Senior-Design-3D-Printing/files/1896932/round_box.zip)
i've redone the file.
