### ISSUE TITLE
Zotikon

### ISSUE THREAD

**Issue by WhoFama24** [msudesign/Senior-Design-3D-Printing#37]
[Athlete-Worn Device.zip](https://github.com/msudesign/Senior-Design-3D-Printing/files/1921452/Athlete-Worn.Device.zip)

We need 2 prints of both models.

**Comment by msudesign** [comment]
Should be ready in the morning, printing in orange as that is what is available.

**Comment by WhoFama24** [comment]
Where should I pick them up?
