### ISSUE TITLE
BPR Attempt

### ISSUE THREAD

**Issue by bestes94** [msudesign/Senior-Design-3D-Printing#5]
[BPR2.0.stl.zip](https://github.com/msudesign/Senior-Design-3D-Printing/files/1335444/BPR2.0.stl.zip)

There should be two separate pieces when printed.

**Comment by msudesign** [comment]
This part is too large to print.
Please keep in mind our print capabilities are : 8.8 x 8.8 x 12.0 inches

**Comment by bestes94** [comment]
[BPR2.0-2.stl.zip](https://github.com/msudesign/Senior-Design-3D-Printing/files/1338075/BPR2.0-2.stl.zip)

**Comment by msudesign** [comment]
The software still does not like the size.
Looking at the files, the best way to print the object will be in 4 pieces. 

The way the object(s) are currently oriented, it will take significantly longer to print to due the fact of printing the support structure.

If you have any questions, please feel free to stop by my office.

**Comment by bestes94** [comment]
[Archive.zip](https://github.com/msudesign/Senior-Design-3D-Printing/files/1338562/Archive.zip)

**Comment by msudesign** [comment]
Please lay the objects flat. When I attempt this in the software it shows the part as not being truly vertical, so it will not lay flat at 0 degrees.

**Comment by msudesign** [comment]
I placed the part that was printed on your workbench. Looked at though there are some areas that need to be address, you will see the crack at the top of the object.

I will hold off on printing the remaining parts for now.

**Comment by bestes94** [comment]
[Archive.zip](https://github.com/msudesign/Senior-Design-3D-Printing/files/1353931/Archive.zip)

I made some changes to fix some of the problem areas hopefully
